### ISSUE TITLE
Cannot read property 'content' of undefined for components with no style tags.

### ISSUE THREAD

**Issue by edanweis** [WJCHumble/vite-plugin-vue2-css-vars#2]
When components or dependencies have no style tags in them, I get error:

`[vite] Internal server error: Cannot read property 'content' of undefined`

**Comment by WJCHumble** [comment]
@edanweis  It was fixed in `0.1.9`.

**Comment by edanweis** [comment]
That was fast. @WJCHumble but now I am getting:

`Internal server error: TypeError: Cannot read property 'spaces' of undefined`

in two of my components.

**Comment by WJCHumble** [comment]
@edanweis Can you provide a reproduction? I am not sure what is it problem.

**Comment by edanweis** [comment]
I discovered it was a missing dependency, but when using `vite-plugin-vue2-css-vars` with pnpm, the missing dependency error was not handled or shown in console. I am working through other problems and will create more issues as I go. Thanks Wu
